---
- name: Deploy Production Application
  hosts: web
  become: true

  tasks:

    - name: Pull latest Docker image
      community.docker.docker_image:
        name: omarhazem13/production-devops-app:latest
        source: pull

    - name: Remove old container
      community.docker.docker_container:
        name: devops-web
        state: absent

    - name: Run production container
      community.docker.docker_container:
        name: devops-web
        image: omarhazem13/production-devops-app:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
