apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: devops-app

  template:
    metadata:
      labels:
        app: devops-app

    spec:
      containers:
        - name: devops-app
          image: omarhazem13/production-devops-app:latest

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"

            limits:
              cpu: "200m"
              memory: "64Mi"
